version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: groupworks_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: groupworks_redis
    ports:
      - "6379:6379"

networks:
  groupworks-network:
    driver: bridge

volumes:
  mongo_data: